image: node:lts

stages: 
  - deploy

before_script:
  - corepack enable
  - corepack prepare pnpm@latest --activate
  - pnpm config set store-dir .pnpm-store

pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: pnpm
    paths:
      - node_modules/
  script:
    - pnpm install
    - pnpm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH